### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by WhiteMagicRaven** [andkrau/NuanceResurrection#23]
Hello, Thank you very much for this awesome project.
Happy new year! )
Can you give us a little gift for new year? )))) Release 0.6.5 version

**Comment by toxieainc** [comment]
True, sounds like a good plan, will do later-on..

**Comment by toxieainc** [comment]
Done.. Enjoy.. :)

**Comment by WhiteMagicRaven** [comment]
thank you)
