### ISSUE TITLE
version 65 shader compiling issue?

### ISSUE THREAD

**Issue by gwald** [andkrau/NuanceResurrection#27]
Hi again :)

Version 065 seems to have shader compiling issues?

![image](https://github.com/andkrau/NuanceResurrection/assets/4924613/9b4c6b8c-167c-4958-a04c-630e9a3d1f1c)

Version 064 runs fine for me.
![image](https://github.com/andkrau/NuanceResurrection/assets/4924613/73bd426f-b88d-462e-a824-b3ee5101566e)

And using the version 064 video_m32_o32.fs video_m32_o32_crt.fs files fixes the problem, so I'm guessing there's a bug there?
I'm not familiar enough with shader programing to pin point the problem but I would guess it's got something to do with these new lines:
uv = clamp(uv,vec2(0.,0.),vec2((720-1)*scaleInternal.x,(resy-1.)*scaleInternal.y));

I'm using Chomp game sample from the SDK2
[cd_app.cof.zip](https://github.com/andkrau/NuanceResurrection/files/14322147/cd_app.cof.zip)

**Comment by toxieainc** [comment]
Could you please try changing `(720-1)` with `(float)(720-1)` ?

**Comment by gwald** [comment]
that complained about the bracket which is strange...
![image](https://github.com/andkrau/NuanceResurrection/assets/4924613/008270f0-bf04-4afa-ab24-d7f4209b987d)

But replacing all (720-1) with (720.0-1.0) worked fine.
Thanks for that.
