### ISSUE TITLE
Nuance doesn't work with frontends or command line

### ISSUE THREAD

**Issue by kaddisemu** [andkrau/NuanceResurrection#4]
Hi,
I am trying to run Nuance with the frontend Launchbox, however it doesn't run the "nuon.run" file, it just closes Nuance. I tried using a program called NWrap to launch the game, but it only works with Nuance 0.51 and not the latest version. 

If I try to use it with Nuance 0.62 it locks up and shows a black screen. Here is a link to NWrap: https://www.thehelper.net/threads/full-screen-nuance-wrapper.120460/
An account is required to download. Here is a mirror:
https://files.catbox.moe/n2fv8v.zip

**Comment by toxieainc** [comment]
Hi!

Unfortunately i have no clue how NWrap works internally, so i just added support to pass a file directly via command line to Nuance itself.
This will then load the file and launch Nuance in fullscreen, too.

Is this sufficient to replace NWrap for launcher-usage?

**Comment by toxieainc** [comment]
Here the release if you want to try: https://github.com/andkrau/NuanceResurrection/releases/tag/0.6.3

**Comment by kaddisemu** [comment]
Thank you!

**Comment by toxieainc** [comment]
No prob. Please verify if this can work with Launchers as intended.

**Comment by toxieainc** [comment]
One more thing for example would be: Can the launcher terminate it? Or must there be some mechanism added to allow for this?

**Comment by toxieainc** [comment]
Could you please verify launcher usage with https://github.com/andkrau/NuanceResurrection/releases/tag/0.6.4 ?

**Comment by toxieainc** [comment]
ping @kaddisemu

**Comment by WhiteMagicRaven** [comment]
I think its up to NWrap developer, so he need update NWrap to support new Nuance version.

**Comment by WhiteMagicRaven** [comment]
"I am trying to run Nuance with the frontend Launchbox," Tested my self with new version , seems works, ok.

**Comment by toxieainc** [comment]
Thanks!
