### ISSUE TITLE
Does NUON have 3d hardware?

### ISSUE THREAD

**Issue by WhiteMagicRaven** [andkrau/NuanceResurrection#5]
As title says
Does NUON have 3d hardware?
it looks like Merlin Racing is rendered by dedicated 3d hardware?
or its rendered entirely by CPU? and that Linear texture filtering is also CPU software implementetion?

**Comment by toxieainc** [comment]
By a traditional definition of a GPU, it does not feature 3d hardware (e.g. dedicated raster units, tex filtering, etc)
BUT it has special instructions to help with a lot of things that are needed to compute 3d graphics (e.g. to allow for fast bilerp texture access, incl. mipmaps, and to do fast 3d math computations). Also, it features (in principal) quite some concepts that were found later-on in e.g. the Cell chip or even (to some extent) in modern SMs of GPUs.
