### ISSUE TITLE
file association bugs Nuance.

### ISSUE THREAD

**Issue by WhiteMagicRaven** [andkrau/NuanceResurrection#6]
If i associate *.CD , *.RUN, *.COF *.APP files with Nuance, so by double clicking on them i assume it goes emulate them.
Like i use command line "nuance.exe c:\somedir\somegame\nuon.cd". this works

In my association it doesn't, it says errors - some files missed.

bios.con and minibios.cof missed.

File association 0 how it works? It is the same as cmd line "exe and fullpatch to open it"
Can be fixed? Its much easier to have that association rather than command line or always browse for that file

**Comment by WhiteMagicRaven** [comment]
retested this by removing all spaces in filenames and it works! So all that errors seems comes from quote errors in cmdline
https://github.com/andkrau/NuanceResurrection/issues/7

**Comment by toxieainc** [comment]
Should work with latest build now, will upload new package.

**Comment by toxieainc** [comment]
https://github.com/andkrau/NuanceResurrection/releases/tag/0.6.4
