### ISSUE TITLE
Command line that contains quotes in patch to file broking emulator ("New Folder")

### ISSUE THREAD

**Issue by WhiteMagicRaven** [andkrau/NuanceResurrection#7]
Command line like
Nuance.exe "c:\New Folder\Ambient Monsters\NUON.CD"

Leads emulator to error:
"Cannot open file or Invalid COFF or NUONROM-DISK file"

for now i have solution is to manually remove these "" quotes and it work, this ones automatically pasted by cmd when i press TAB for completion.

I even tested what will happen if i use single quotes
Nuance.exe 'c:\New Folder\Ambient Monsters\NUON.CD'

Happens same error. Seems emulator itself doesn't love quotes.

**Comment by toxieainc** [comment]
Should work with latest build now, will upload new package.

**Comment by toxieainc** [comment]
https://github.com/andkrau/NuanceResurrection/releases/tag/0.6.4
